#!/bin/sh

# Remove files generated by all projects.
rm -fv condor.log
rm -fv condor.out
rm -fv condor.err
rm -fv CommandPlatform.exe
rm -fv hw.tar.gz

# Remove folders generated by this project:
rm -fv sys_output_*

# Remove files generated by this project:
rm -fv TBL_train.sh
rm -fv TBL_classify.sh
