#!/bin/sh

# Remove files generated by all projects.
rm -fv condor.log
rm -fv condor.out
rm -fv condor.err
rm -fv CommandPlatform.exe
rm -fv hw.tar.gz

# Remove folders generated by this project:


# Remove files generated by this project:
rm -fv svm_classify.sh
rm -f model.*
rm -f sys.*
rm -f acc.*
rm -f output.*
