//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ericmclachlan.Portfolio.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ericmclachlan.Portfolio.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talk.politics.guns  a:1 after:1 amend:1 an:1 and:1 are:1 article:1 att:1 available:1 be:1 been:1 big:1 bill:1 c:1 cb:1 cbnews:1 cipriani:1 code:1 com:1 date:1 demonstrated:1 down:1 ensure:1 ever:1 final:1 government:1 graph:1 gridlock:1 growth:1 h:1 handgun:1 handguns:1 has:1 in:1 individual:1 is:1 issued:1 knowledge:1 larry:1 licensed:1 licensing:1 lvc:1 maintenance:1 may:1 mechanism:1 not:1 note:1 nu:1 of:1 on:1 only:1 or:1 para:1 paragraph:1 permit:1 persons:1 possess:1 posting:1 prescribed:1 pretending: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeatureVectors_test {
            get {
                return ResourceManager.GetString("FeatureVectors_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talk.politics.guns  a:1 about:1 absurd:1 again:1 an:1 and:1 any:1 approaching:1 are:1 argument:1 article:1 as:1 associates:1 at:1 average:1 bait:1 be:1 being:1 betraying:1 better:1 bms:1 by:1 c:1 calculator:1 capita:1 choice:1 chrissakes:1 citizen:1 com:1 crow:1 dangerous:1 deaths:1 die:1 easier:1 eigth:1 enuff:1 expressed:1 feel:1 fifth:1 for:1 former:1 given:1 had:1 hambidge:1 handgun:1 has:1 hav:1 here:1 higher:1 homicides:1 how:1 i:1 if:1 importantly:1 in:1 individual:1 is:1 it:1 killed:1 lack:1 latter: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeatureVectors_train {
            get {
                return ResourceManager.GetString("FeatureVectors_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svm_type c_svc
        ///kernel_type linear
        ///nr_class 2
        ///total_sv 535
        ///rho 0.281122
        ///label 0 1
        ///nr_sv 272 263
        ///SV
        ///0.004437478408154137 0:1 1:1 2:1 3:1 4:1 5:1 6:1 7:1 8:1 9:1 10:1 11:1 12:1 13:1 14:1 15:1 16:1 17:1 18:1 19:1 20:1 21:1 22:1 23:1 24:1 25:1 26:1 27:1 28:1 29:1 30:1 31:1 32:1 33:1 34:1 35:1 36:1 37:1 38:1 39:1 40:1 41:1 42:1 43:1 44:1 45:1 46:1 47:1 48:1 49:1 50:1 51:1 52:1 53:1 54:1 55:1 56:1 57:1 58:1 59:1 60:1 61:1 62:1 63:1 64:1 65:1 66:1 67:1 68:1 69:1 70:1 71:1 72:1 73:1 74:1 75:1 76:1 77:1 78:1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string libSVM_model {
            get {
                return ResourceManager.GetString("libSVM_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0:1 4:1 5:1 8:1 10:1 16:1 22:1 28:1 44:1 45:1 54:1 55:1 56:1 70:1 80:1 82:1 84:1 94:1 110:1 111:1 116:1 126:1 131:1 146:1 180:1 189:1 279:1 314:1 317:1 364:1 380:1 400:1 407:1 421:1 423:1 509:1 516:1 533:1 562:1 730:1 835:1 920:1 941:1 993:1 1168:1 1214:1 1295:1 1341:1 1343:1 1392:1 1404:1 1504:1 1632:1 1829:1 2057:1 2282:1 2445:1 2564:1 2569:1 2572:1 2573:1 2574:1 2589:1 3223:1 3420:1 3641:1 3892:1 4404:1 5002:1 5038:1 6274:1 6392:1 6579:1 7171:1 7225:1 7327:1 7494:1 7927:1 8028:1 8031:1 8038:1 9964:1 11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string libSVM_test {
            get {
                return ResourceManager.GetString("libSVM_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0:1 1:1 2:1 3:1 4:1 5:1 6:1 7:1 8:1 9:1 10:1 11:1 12:1 13:1 14:1 15:1 16:1 17:1 18:1 19:1 20:1 21:1 22:1 23:1 24:1 25:1 26:1 27:1 28:1 29:1 30:1 31:1 32:1 33:1 34:1 35:1 36:1 37:1 38:1 39:1 40:1 41:1 42:1 43:1 44:1 45:1 46:1 47:1 48:1 49:1 50:1 51:1 52:1 53:1 54:1 55:1 56:1 57:1 58:1 59:1 60:1 61:1 62:1 63:1 64:1 65:1 66:1 67:1 68:1 69:1 70:1 71:1 72:1 73:1 74:1 75:1 76:1 77:1 78:1 79:1 80:1 81:1 82:1 83:1 84:1 85:1 86:1 87:1 88:1 89:1 90:1 91:1 92:1 93:1 94:1 95:1 96:1 97:1 98:1 99:1 100:1 101:1 102:1 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string libSVM_train {
            get {
                return ResourceManager.GetString("libSVM_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURES FOR CLASS NNP
        /// &lt;default&gt; 3.7912278052488615
        /// curW=Pierre 1.0055824571891294
        /// prevW=BOS 0.15158438156724433
        /// prev2W=BOS -0.042484272090335465
        /// next2W=comma 0.7376566212571102
        /// prevT=BOS 0.15158438156724433
        /// prevTwoTags=BOS+BOS 0.15158438156724433
        /// nextW=comma 0.9811762303347142
        /// next2W=61 0.10291483661846342
        /// prevT=NNP 2.689252489575855
        /// prevTwoTags=BOS+NNP 0.35960803637958344
        /// containUC 3.966119316223147
        /// pref=V 0.5261420258668185
        /// pref=Vi -0.41208112866815233
        /// suf=n -0.3092633085823188
        /// suf=en -0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaxEnt_Model {
            get {
                return ResourceManager.GetString("MaxEnt_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURES FOR CLASS talk.politics.guns
        /// &lt;default&gt; -0.1583551304403412
        /// a -0.18898126800339418
        /// about 0.0832704303587203
        /// absurd 0.08705561748697474
        /// again -0.19321273294161795
        /// an -0.17024317523326235
        /// and 0.24996307517095412
        /// any -0.0769791550753222
        /// approaching -0.021386303178712065
        /// are -0.20894266136570772
        /// argument -0.057778623605044696
        /// article -0.21237035159475048
        /// as 0.20698090761272375
        /// associates 0.07576433030431617
        /// at -0.07586261853721844
        /// average 0.057213133953750335
        /// bait 0.1937802611630568
        /// be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Model_MaxEnt_Mallet {
            get {
                return ResourceManager.GetString("Model_MaxEnt_Mallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21-0-The DT curW=The 1 prevW=BOS 1 prev2W=BOS 1 nextW=proposed 1 next2W=holding 1
        ///21-1-proposed JJ curW=proposed 1 prevW=The 1 prev2W=BOS 1 nextW=holding 1 next2W=company 1
        ///21-2-holding NN curW=holding 1 prevW=proposed 1 prev2W=The 1 nextW=company 1 next2W=would 1
        ///21-3-company NN curW=company 1 prevW=holding 1 prev2W=proposed 1 nextW=would 1 next2W=also 1
        ///21-4-would MD curW=would 1 prevW=company 1 prev2W=holding 1 nextW=also 1
        ///21-5-also RB curW=also 1 prevW=would 1 prev2W=company 1 next2W=Great 1
        ///21-6-conso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string POS_Vectors {
            get {
                return ResourceManager.GetString("POS_Vectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string POS_Vectors_Boundaries {
            get {
                return ResourceManager.GetString("POS_Vectors_Boundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talk.politics.guns  a:1 after:1 amend:1 an:1 and:1 are:1 article:1 att:1 available:1 be:1 been:1 big:1 bill:1 c:1 cb:1 cbnews:1 cipriani:1 code:1 com:1 date:1 demonstrated:1 down:1 ensure:1 ever:1 final:1 government:1 graph:1 gridlock:1 growth:1 h:1 handgun:1 handguns:1 has:1 in:1 individual:1 is:1 issued:1 knowledge:1 larry:1 licensed:1 licensing:1 lvc:1 maintenance:1 may:1 mechanism:1 not:1 note:1 nu:1 of:1 on:1 only:1 or:1 para:1 paragraph:1 permit:1 persons:1 possess:1 posting:1 prescribed:1 pretending: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SVMLight_TestVectors {
            get {
                return ResourceManager.GetString("SVMLight_TestVectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talk.politics.guns  a:1 about:1 absurd:1 again:1 an:1 and:1 any:1 approaching:1 are:1 argument:1 article:1 as:1 associates:1 at:1 average:1 bait:1 be:1 being:1 betraying:1 better:1 bms:1 by:1 c:1 calculator:1 capita:1 choice:1 chrissakes:1 citizen:1 com:1 crow:1 dangerous:1 deaths:1 die:1 easier:1 eigth:1 enuff:1 expressed:1 feel:1 fifth:1 for:1 former:1 given:1 had:1 hambidge:1 handgun:1 has:1 hav:1 here:1 higher:1 homicides:1 how:1 i:1 if:1 importantly:1 in:1 individual:1 is:1 it:1 killed:1 lack:1 latter: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SVMLight_TrainVectors {
            get {
                return ResourceManager.GetString("SVMLight_TrainVectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talk.politics.guns 
        ///israel talk.politics.guns talk.politics.mideast 323
        ///turkish talk.politics.guns talk.politics.mideast 181
        ///clayton talk.politics.guns talk.politics.misc 111
        ///money talk.politics.guns talk.politics.misc 82
        ///arab talk.politics.guns talk.politics.mideast 63
        ///muslims talk.politics.guns talk.politics.mideast 46
        ///president talk.politics.guns talk.politics.misc 40
        ///israeli talk.politics.guns talk.politics.mideast 36
        ///health talk.politics.guns talk.politics.misc 35
        ///hallam talk.politics.guns talk.politic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TBLModel {
            get {
                return ResourceManager.GetString("TBLModel", resourceCulture);
            }
        }
    }
}
